### ISSUE TITLE
Allow configurable weighting between the outputs

### ISSUE THREAD

**Issue by stevenaeola** [lutzer/node-red-contrib-random-output#1]
The idea is that a set of non-negative weightings is defined for the outputs, which default to 1 for each output. The sum of the weightings has to be greater than zero. Then the weightings are used to define the probability for each output. I was going to write my own node to do this, but given that you already have defined a node, are you open to a pull request?

**Comment by lutzer** [comment]
sure. go ahead. i will merge it in.
