### ISSUE TITLE
When DEPLOY example flow - i see error in console: "TypeError: config.weights is not iterable"

### ISSUE THREAD

**Issue by Dukuu-Wild** [lutzer/node-red-contrib-random-output#3]
![image](https://user-images.githubusercontent.com/20105241/149480104-c2744c00-b5de-4516-9ee1-df5ec64c8ec6.png)

msg : error
"TypeError: config.weights is not iterable"

STR:
I imported example to my local node-red.
I press deploy

Expected: deploy and example works

Actual:
error (see above) is shown
injecting doesn't operate (and doesn't add console logs)

**Comment by lutzer** [comment]
thanks. it was probably an outdated example. the node should work fine however. i fixed the example

**Comment by Dukuu-Wild** [comment]
Now works, thanks!
